import File.expand_path("../tasks/Rakefile", __dir__)

desc "Install playwright drivers using npm"
task :setup_playwright do
  sh "npm install playwright"
  sh "./node_modules/.bin/playwright install"
end
